export default imagePaths = [
  { src: "12.png", animation: secondImg },
  { src: "13.png", animation: firstImg },
  { src: "14.png", animation: fourthImg },
  { src: "335.png", animation: secondImg },
  { src: "slideshow/100.png", animation: thirdImg },
  { src: "slideshow/102.png", animation: thirdImg },
  { src: "slideshow/Cyndi Lauper Cheetah.png", animation: thirdImg },
  { src: "slideshow/Serena Williams Cheetah.png", animation: thirdImg },
  { src: "slideshow/Skylar Diggins-Smith Cheetah.png", animation: thirdImg },
  { src: "slideshow/Wonder Woman Cheetah.png", animation: thirdImg },
  { src: "slideshow/923.png", animation: thirdImg },
  { src: "slideshow/989.png", animation: thirdImg },
  { src: "slideshow/995.png", animation: thirdImg },
  { src: "slideshow/1014.png", animation: thirdImg },
  { src: "slideshow/1007.png", animation: thirdImg },
  { src: "slideshow/1017.png", animation: thirdImg },
  { src: "slideshow/105.png", animation: thirdImg },
  { src: "slideshow/107.png", animation: thirdImg },
  { src: "slideshow/108.png", animation: thirdImg },
  { src: "slideshow/109.png", animation: thirdImg },
  { src: "slideshow/110.png", animation: thirdImg },
  { src: "slideshow/112.png", animation: thirdImg },
  { src: "slideshow/124.png", animation: thirdImg },
  { src: "slideshow/139.png", animation: thirdImg },
  { src: "slideshow/140.png", animation: thirdImg },
  { src: "slideshow/92.png", animation: thirdImg },
  { src: "slideshow/93.png", animation: thirdImg },
  { src: "Damian lillard.png", animation: firstImg },
  { src: "james harden1.png", animation: secondImg },
  { src: "jazz 1.png", animation: thirdImg },
  { src: "Luke doncic.png", animation: fourthImg },
  { src: "MGK.png", animation: firstImg },
  { src: "pink panther.png", animation: secondImg },
  { src: "rapper 1.png", animation: thirdImg },
  { src: "snowbording cheetah.jpg", animation: fourthImg },
  { src: "Tom Brady 1.png", animation: firstImg },
  { src: "17.png", animation: firstImg },
  { src: "18.png", animation: secondImg },
  { src: "19.png", animation: secondImg },
  { src: "139.png", animation: secondImg },
  { src: "147.png", animation: secondImg },
  { src: "148.png", animation: secondImg },
  { src: "149.png", animation: secondImg },
  { src: "5521.png", animation: secondImg },
  { src: "569.png", animation: secondImg },
  { src: "520.png", animation: secondImg },
  { src: "335.png", animation: secondImg },
  { src: "162.png", animation: secondImg },
];
